site_name: Johnson Loh
site_url: https://johndotl.com/

repo_url: https://github.com/Bobinator7/Bobinator7.github.io

docs_dir: 'docs'

nav:
  - Home: index.md

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences